[package]
name = "bevy_fmod"
description = "Idiomatic FMOD in Bevy"
authors = ["Fabian 'Salzian' Fritzsche <bevy_fmod@salzian.dev>"]
edition = "2021"
repository = "https://github.com/salzian/bevy_fmod"
version = "0.5.0"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0"
bevy = { version = "0.14", default-features = false }
bevy_mod_sysfail = "3.0"
libfmod = "~2.222.3"

[dev-dependencies.bevy]
version = "0.14"
features = [
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_winit",
    "multi_threaded"
]

[features]
default = []
live-update = []

[[example]]
name = "minimal"

[[example]]
name = "audio_control"

[[example]]
name = "spatial"

[[example]]
name = "parameters"

