[package]
name = "bevy_fmod"
description = "Idiomatic FMOD in Bevy"
authors = ["Fabian 'Salzian' Fritzsche <bevy_fmod@salzian.dev>"]
edition = "2021"
repository = "https://github.com/salzian/bevy_fmod"
version = "0.2.0"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.75"
bevy = { version = "0.11.2", default-features = false, features = ["bevy_audio"] }
bevy_mod_sysfail = "3.0.0"
libfmod = "2.206.2"
log = "0.4.20"

[dev-dependencies]
# The examples need the default features of bevy
bevy = { version = "0.11.2", default-features = true }
smooth-bevy-cameras = "0.9.0"

[features]
default = []

# This is some documentation.
live-update = []

[[example]]
name = "minimal"

[[example]]
name = "spatial"
